services:
  pocketbase:
    container_name: pocketbase
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    restart: unless-stopped
    user: 0:0
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_data:/pb_data

  server:
    container_name: shorl-server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - POCKETBASE_URL=http://pocketbase:8090

  web:
    container_name: shorl-web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - POCKETBASE_URL=http://localhost:8090 # change if deploying on a different url
