import { Alert, Button, Flex, PasswordInput, TextInput, Title } from "@mantine/core";

import { isNotEmpty, useForm } from "@mantine/form";
import { ClientResponseError } from "pocketbase";
import { useNavigate } from "react-router-dom";
import pocketbase from "../../../pocketbase";

export default function RegisterForm({ setAlert }: { setAlert: (alert: ReturnType<typeof Alert>) => void }) {
  const navigate = useNavigate();

  const form = useForm({
    initialValues: {
      username: "",
      password: "",
      passwordConfirm: "",
    },
    validate: {
      password: isNotEmpty("Password is required"),
      passwordConfirm: (value, values) => {
        if (value !== values.password) return "Passwords do not match";
      },
    },
  });

  return (
    <Flex direction="column" justify="center" miw="30%" w="auto">
      <Title order={1}>Register</Title>
      <Flex
        component="form"
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore lmao eslint ồn thật
        onSubmit={form.onSubmit(async (values) => {
          try {
            await pocketbase.collection("users").create({
              username: values.username,
              password: values.password,
              passwordConfirm: values.passwordConfirm,
            });
          } catch (error) {
            if (error instanceof ClientResponseError)
              setAlert(
                <Alert color="red" title="Error" onClose={() => setAlert(undefined)}>
                  {error.message}
                </Alert>
              );
          }

          navigate("/");
        })}
      >
        <Flex mt="xl" direction="column">
          <TextInput label="Username" placeholder="Autogenerated if blank" key={form.key("username")} {...form.getInputProps("username")} />
          <PasswordInput
            mt="sm"
            label="Password"
            placeholder="Enter your password"
            required
            key={form.key("password")}
            {...form.getInputProps("password")}
          />
          <PasswordInput
            mt="sm"
            label="Confirm Password"
            placeholder="Confirm your password"
            required
            key={form.key("passwordConfirm")}
            {...form.getInputProps("passwordConfirm")}
          />
          <Flex mt="xl">
            <Button color="cyan" type="submit">
              Register
            </Button>
          </Flex>
        </Flex>
      </Flex>
    </Flex>
  );
}
